// fontend/front-react/src/views/Login/Login.tsx
import React from 'react'
import styles from './Login.module.scss'
import { Button, message, Form, Input, Row, Col } from 'antd'
import { useAppDispatch } from '../../store'
import { loginAction, updateToken } from '../../store/modules/users'
import classNames from 'classnames'
import { useNavigate } from 'react-router-dom'

interface User {
  email: string
  pass: string
}

const testUsers: User[] = [
  {
    email: 'huangrong@gmail.com',
    pass: 'huangrong'
  },
  {
    email: 'hongqigong@gmail.com',
    pass: 'hongqigong'
  }
];

export default function Login() {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()
  const [form] = Form.useForm()

  const onFinish = (values: User) => {
    dispatch(loginAction(values)).then((action)=>{
      const {errcode, token} = (action.payload as {[index: string]: unknown}).data as {[index: string]: unknown}
      if( errcode === 0 && typeof token === 'string' ){
        dispatch(updateToken(token))
        message.success('登录成功');
        navigate('/');
      }
      else{
        message.error('登录失败');
      }
    })
  };
  const onFinishFailed = ({values}: {values: User}) => {
    console.log('Failed:', values);
  };
  const autoLogin = (values: User) => {
    return ()=>{
      form.setFieldsValue(values)  // 设置数据的回显
      onFinish(values)
    }
  }
  return (
    <div className={styles.login}>
      <div className={styles.header}>
        <span className={styles['header-logo']}>
          <i className={classNames('iconfont icon-react', styles['icon-react'])}></i>
          <i className={classNames('iconfont icon-icon-test', styles['icon-icon-test'])}></i>
          <i className={classNames('iconfont icon-typescript', styles['icon-typescript'])}></i>
        </span>
        <span className={styles['header-title']}>在线考勤系统</span>
      </div>
      <div className={styles.desc}>
        React + typescript + react-redux + redux-persist
      </div>
      <Form
        name="basic"
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 18 }}
        initialValues={{ remember: true }}
        onFinish={onFinish}
        onFinishFailed={onFinishFailed}
        autoComplete="off"
        className={styles.main}
        form={form}
      >
        <Form.Item
          label="邮箱"
          name="email"
          rules={[
            { required: true, message: '请输入邮箱' },
            { type: 'email', message: '请输入正确的邮箱地址' }
          ]}
        >
          <Input placeholder="请输入邮箱" />
        </Form.Item>

        <Form.Item
          label="密码"
          name="pass"
          rules={[{ required: true, message: '请输入密码' }]}
        >
          <Input.Password placeholder="请输入密码" visibilityToggle={false} />
        </Form.Item>
        <Form.Item wrapperCol={{ offset: 6, span: 18 }}>
          <Button type="primary" htmlType="submit">
            登录
          </Button>
        </Form.Item>
      </Form>
      <div className={styles.users}>
        <Row gutter={20}>
          {
            testUsers.map((v)=> (
              <Col key={v.email} span={12}>
                <h3>
                  测试账号，<Button onClick={autoLogin({email: v.email, pass: v.pass})}>一键登录</Button>
                </h3>
                <p>邮箱：{v.email}</p>
                <p>密码：{v.pass}</p>
              </Col>
            ))
          }
        </Row>
      </div>
    </div>
  )
}

// fontend/front-vue/src/views/Login/Login.vue
<template>
  <div class="login">
    <div class="header">
      <span class="header-logo">
        <i class="iconfont icon-vue"></i>
        <i class="iconfont icon-icon-test"></i>
        <i class="iconfont icon-typescript"></i>
      </span>
      <div class="header-title">在线考勤系统</div>
    </div>
    <div class="desc">
      vue3 + vue-router + vuex + vuex-persist + lodash + elementPlus 
    </div>
    <el-form
      ref="ruleFormRef"
      :model="ruleForm"
      :rules="rules"
      label-width="auto"
      class="main"
    >
    <el-form-item label="邮箱" prop="email">
      <el-input v-model="ruleForm.email" type="text" placeholder="请输入邮箱" />
    </el-form-item>
    <el-form-item label="密码" prop="pass">
      <el-input v-model="ruleForm.pass" type="password" placeholder="请输入密码" />
    </el-form-item>
    <el-form-item label="   ">
      <el-button type="primary" @click="submitForm(ruleFormRef)" auto-insert-space>
        登陆
      </el-button>
    </el-form-item>
    </el-form>
    <div class="users">
      <el-row :gutter="20">
        <el-col :span="12" v-for="item in testUsers" :key="item.email">
          <h3>
            测试帐号，<el-button @click="autoLogin(item)">一键登陆</el-button>
          </h3>
          <p>邮箱：{{item.email}}</p>
          <p>密码：{{item.pass}}</p>
          <p></p>
        </el-col>
      </el-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineComponent, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import { useStore } from '@/store';
import type { FormInstance, FormRules } from 'element-plus'
import { useRouter } from 'vue-router';
const store = useStore()
const router = useRouter()
defineComponent({
  name: 'LoginView'
})

interface User {
  email: string
  pass: string
}



const ruleFormRef = ref<FormInstance>()

const ruleForm = reactive<User>({
  email:'',
  pass: ''
})

const rules = reactive<FormRules<typeof ruleForm>>({
  email: [
    { required: true, message: "请输入邮箱", trigger: 'blur' },
    { type: 'email', message: '请输入正确的邮箱地址', trigger: 'blur' }
  ],
  pass: [
    { required: true, message: "请输入密码", trigger: 'blur' }
  ]
})

const testUsers: User[] = [
  {
    email: 'huangrong@gmail.com',
    pass: 'huangrong'
  },
  {
    email: 'hongqigong@gmail.com',
    pass: 'hongqigong'
  }
] 

const submitForm = (formEl: FormInstance | undefined) => {
  if (!formEl) return
  formEl.validate((valid) => {
    if (valid) {
      store.dispatch("users/login", ruleForm).then(res => {
        if(res.data.errcode === 0) {
          store.commit('users/updateToken', res.data.token)
          ElMessage.success('登陆成功')
          router.push('/')
        } else {
          ElMessage.error('登陆失败')
        }
      })
    } else {
      console.log('error submit!')
    }
  })
}

const autoLogin = (user: User) => {
  ruleForm.email = user.email
  ruleForm.pass = user.pass
  submitForm(ruleFormRef.value)
}

</script>

<style scoped lang="scss">
.login {
  width: 100vw;
  height: 100vh;
  background: url('@/assets/images/login-bg.svg') no-repeat center 110px;
  background-size: 100%;
  .header {
    height: 44px;
    line-height: 44px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 34px;
    padding-top: 100px;

    .header-logo {
      .icon-vue,.icon-icon-test,.icon-typescript {
        margin-right: 5px;
        font-size: inherit;
      }
      .icon-vue {
        color: green;
      }
      .icon-icon-test {
        color: #deb887;
      }
      .icon-typescript {
        color: blue;
      }
    }
    .header-title {
      margin-left: 30px;
      font-weight: 700;
      font-size: 30px;
    }
  }
  .desc {
    text-align: center;
    padding-top: 30px;
    color: rgba(0,0,0,.45);
    font-size: 16px;
  }
  .main {
    width: 500px;
    margin: 0 auto;
    padding-top: 50px;
  }
  .users {
    width: 500px;
    margin: 60px auto;
    color: rgba(0,0,0,.65);
    h3 {
      font-size: 16px;
    }
    p {
      margin: 20px;
    }
  }
}
</style>
