// fontend/front-react/src/views/Apply/Apply.tsx
import React, { useState, useEffect } from 'react'
import styles from './Apply.module.scss'
import { Row, Button, Space, Input, Divider, Radio, Table, Modal, Form, Select, DatePicker, message } from 'antd'
import type { RadioChangeEvent } from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import type { ColumnsType } from 'antd/es/table'
import type { Infos } from '../../store/modules/checks'
import { useSelector } from 'react-redux'
import { useAppDispatch } from '../../store'
import type { RootState } from '../../store'
import _ from 'lodash'
import { getApplyAction, postApplyAction, updateApplyList } from '../../store/modules/checks'
import 'dayjs/locale/zh-cn';
import locale from 'antd/es/date-picker/locale/zh_CN';
import dayjs from 'dayjs'
import { putRemindAction, updateInfo } from '../../store/modules/news'
import type { Info } from '../../store/modules/news'

interface FormInfos {
  approvername: string
  note: string
  reason: string
  time: [string, string]
}

const approverTypes = [
  {label: '全部', value: '全部'},
  {label: '待审批', value: '待审批'},
  {label: '已通过', value: '已通过'},
  {label: '未通过', value: '未通过'}
];
const defaultType = approverTypes[0].value;
const columns: ColumnsType<Infos> = [
  {
    title: '申请人',
    dataIndex: 'applicantname',
    key: 'applicantname',
    width: 180
  },
  {
    title: '审批事由',
    dataIndex: 'reason',
    key: 'reason',
    width: 180
  },
  {
    title: '时间',
    dataIndex: 'time',
    key: 'time',
    render(_){
      return _.join(' - ')
    }
  },
  {
    title: '备注',
    dataIndex: 'note',
    key: 'note',
  },
  {
    title: '审批人',
    dataIndex: 'approvername',
    key: 'approvername',
    width: 180
  },
  {
    title: '状态',
    dataIndex: 'state',
    key: 'state',
    width: 180
  }
];

export default function Apply() {
  const [ approverType, setApproverType ] = useState(defaultType)
  const [ searchWord, setSearchWord ] = useState('')
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [form] = Form.useForm()
  const usersInfos = useSelector((state: RootState) => state.users.infos)
  const applyList = useSelector((state: RootState)=> state.checks.applyList).filter((v)=> (v.state === approverType || defaultType === approverType) && (v.note as string).includes(searchWord)) 
  const newsInfo = useSelector((state: RootState)=> state.news.info)
  const dispatch = useAppDispatch()
  useEffect(() => {
    if (_.isEmpty(applyList)) {
      dispatch(getApplyAction({ applicantid: usersInfos._id as string })).then(
        (action) => {
          const { errcode, rets } = (
            action.payload as { [index: string]: unknown }
          ).data as { [index: string]: unknown }
          if (errcode === 0) {
            dispatch(updateApplyList(rets as Infos[]))
          }
        }
      )
    }
  }, [applyList, usersInfos, dispatch])

  useEffect(() => {
    if ( newsInfo.applicant ) {
      dispatch(putRemindAction({userid: usersInfos._id as string, applicant: false})).then((action)=>{
        const { errcode, info } = (
          action.payload as { [index: string]: unknown }
        ).data as { [index: string]: unknown }
        if (errcode === 0) {
          dispatch(updateInfo(info as Info))
        }
      })
    }
  }, [dispatch, usersInfos, newsInfo]);

  const approverTypeChange = (ev: RadioChangeEvent) => {
    setApproverType(ev.target.value)
  }
  const searchWordChange  = (ev: React.ChangeEvent<HTMLInputElement>) => {
    setSearchWord(ev.target.value)
  }
  const showModal = () => {
    setIsModalOpen(true);
  };
  const handleCancel = () => {
    setIsModalOpen(false);
    handleReset()
  };
  const onFinish = (values: FormInfos) => {
    values.time[0] = dayjs(values.time[0]).format('YYYY-MM-DD hh:mm:ss')
    values.time[1] = dayjs(values.time[1]).format('YYYY-MM-DD hh:mm:ss')
    const applyList = {
      ...values,
      applicantid: usersInfos._id as string,
      applicantname: usersInfos.name as string,
      approverid: Array.isArray(usersInfos.approver) && usersInfos.approver.find((item)=> item.name === values.approvername)._id
    }
    dispatch(postApplyAction(applyList)).then((action)=>{
      const { errcode } = (
        action.payload as { [index: string]: unknown }
      ).data as { [index: string]: unknown }
      if (errcode === 0) {
        message.success('添加审批成功')
        handleCancel()
        dispatch(getApplyAction({ applicantid: usersInfos._id as string })).then(
          (action) => {
            const { errcode, rets } = (
              action.payload as { [index: string]: unknown }
            ).data as { [index: string]: unknown }
            if (errcode === 0) {
              dispatch(updateApplyList(rets as Infos[]))
            }
          }
        )
        dispatch(putRemindAction({ userid: applyList.approverid, approver: true }))
      }
    })
  };
  const onFinishFailed = ({values}: {values: FormInfos}) => {
    console.log('Failed:', values);
  };
  const handleReset = () => {
    form.resetFields()
  }
  return (
    <div>
      <Row className={styles['apply-title']} justify="space-between">
        <Button type="primary" onClick={showModal}>添加审批</Button>
        <Space>
          <Input placeholder="请输入搜索关键词" value={searchWord} onChange={searchWordChange} />
          <Button type="primary" icon={<SearchOutlined />}>搜索</Button>
          <Divider style={{ borderLeftColor: '#dcdfe6' }} type="vertical" />
          <Radio.Group
            options={approverTypes}
            optionType="button"
            buttonStyle="solid"
            value={approverType}
            onChange={approverTypeChange}
          />
        </Space>
      </Row>
      <Table rowKey="_id" className={styles['apply-table']} dataSource={applyList} columns={columns} bordered size="small" pagination={{defaultPageSize: 5}} />
      <Modal title="添加审批" open={isModalOpen} onCancel={handleCancel} footer={null}>
        <Form
          name="basic"
          labelCol={{ span: 4 }}
          wrapperCol={{ span: 20 }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
          className={styles['apply-form']}
          form={form}
        >
          <Form.Item
            label="审批人"
            name="approvername"
            rules={[
              { required: true, message: '请选择审批人' }
            ]}
          >
            <Select placeholder="请选择审批人" allowClear>
              {
                Array.isArray(usersInfos.approver) && usersInfos.approver.map((item)=> <Select.Option key={item._id} value={item.name}>{item.name}</Select.Option>)
              }
              
            </Select>
          </Form.Item>
          <Form.Item
            label="审批事由"
            name="reason"
            rules={[
              { required: true, message: '请选择审批事由' }
            ]}
          >
            <Select placeholder="请选择审批事由" allowClear>
              <Select.Option value="年假">年假</Select.Option>
              <Select.Option value="事假">事假</Select.Option>
              <Select.Option value="病假">病假</Select.Option>
              <Select.Option value="外出">外出</Select.Option>
              <Select.Option value="补签卡">补签卡</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item
            label="时间"
            name="time"
            rules={[{ required: true, message: '请选择审批时间' }]}
          >
            <DatePicker.RangePicker showTime locale={locale} />
          </Form.Item>
          <Form.Item
            label="备注"
            name="note"
            rules={[{ required: true, message: '请输入备注' }]}
          >
            <Input.TextArea rows={4} placeholder="请输入备注" />
          </Form.Item>
          <Row justify="end">
            <Space>
              <Button onClick={handleReset}>重置</Button>
              <Button type="primary" htmlType="submit">提交</Button>
            </Space>
          </Row>
        </Form>
      </Modal>
    </div>
  )
}

// fontend/front-vue/src/views/Apply/Apply.vue

<template>
  <div class="apply-title">
    <el-button type="primary" @click="handleOpen">添加审批</el-button>
    <el-space>
      <el-input v-model="searchWord" placeholder="请输入搜索关键词"></el-input>
      <el-button type="primary" icon="search">搜索</el-button>
      <el-divider direction="vertical"></el-divider>
      <el-radio-group v-model="approverType">
        <el-radio-button label="全部" value="全部"></el-radio-button>
        <el-radio-button label="待审批" value="待审批"></el-radio-button>
        <el-radio-button label="已通过" value="已通过"></el-radio-button>
        <el-radio-button label="未通过" value="未通过"></el-radio-button>
      </el-radio-group>
    </el-space>
  </div>
  <div class="apply-table">
    <el-table :data="pageApplyList" style="width: 100%" border>
      <el-table-column prop="applicantname" label="申请人" width="180"></el-table-column>
      <el-table-column prop="reason" label="审批事由" width="180"></el-table-column>
      <el-table-column prop="time" label="时间">
        <template #default="scope">
          {{ scope.row.time.join(' ~ ') }}
        </template>
      </el-table-column>
      <el-table-column prop="note" label="备注"></el-table-column>
      <el-table-column prop="approvername" label="审批人" width="180"></el-table-column>
      <el-table-column prop="state" label="状态" width="180"></el-table-column>
    </el-table>
    <el-pagination background layout="prev, pager, next, total" :total="applyList.length" :page-size="pageSize" @current-change="handleChange"></el-pagination>
  </div>
  <el-dialog
    v-model="dialogVisible"
    title="添加审批"
    width="500"
    :before-close="handleClose"
  >
  <el-form
      ref="ruleFormRef"
      :model="ruleForm"
      :rules="rules"
      label-width="80px"
    >
    <el-form-item label="审批人" prop="approvername">
      <el-select v-model="ruleForm.approvername" placeholder="请选择">
        <el-option v-for="item in approver" :key="(item._id as string)" :value="(item.name as string)" :label="(item.name as string)"></el-option>
      </el-select>
    </el-form-item>
    <el-form-item label="审批事由" prop="reason">
      <el-select v-model="ruleForm.reason" placeholder="请选择">
        <el-option value="年假" label="年假"></el-option>
        <el-option value="事假" label="事假"></el-option>
        <el-option value="病假" label="病假"></el-option>
        <el-option value="外出" label="外出"></el-option>
        <el-option value="补签卡" label="补签卡"></el-option>
      </el-select>
    </el-form-item>
    <el-form-item label="时间" prop="time">
      <el-date-picker
        v-model="ruleForm.time"
        type="datetimerange"
        start-placeholder="开始时间"
        end-placeholder="结束时间"
      ></el-date-picker>
    </el-form-item>
    <el-form-item label="备注" prop="note">
      <el-input
        v-model="ruleForm.note"
        :autosize="{ minRows: 4, maxRows: 6 }"
        type="textarea"
        placeholder="请输入"
      ></el-input>
    </el-form-item>
    </el-form>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="resetForm(ruleFormRef)">重 置</el-button>
        <el-button type="primary" @click="submitForm(ruleFormRef)">
          提 交
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed, defineComponent, ref, reactive } from 'vue';
import moment from 'moment';
import { ElMessage } from 'element-plus';
import type {  DateModelType, FormInstance, FormRules } from 'element-plus'
import { useStore } from '@/store';
defineComponent({
  name: 'ApplyView'
})

interface ApplyList {
  applicantid: string,
  applicantname: string,
  approverid: string,
  approvername: string,
  note: string,
  reason: string,
  time: [DateModelType, DateModelType]
}

const store = useStore()
const defaultType = '全部'
const approverType = ref(defaultType)
const searchWord = ref('')
const userInfos = computed(() => store.state.users.infos)
const approver = computed(() => userInfos.value.approver as {[index: string]: unknown}[])
const dialogVisible = ref(false)
const applyList = computed(() => store.state.checks.applyList.filter(v => (v.state === approverType.value || defaultType === approverType.value) && (v.note as string).includes(searchWord.value)))
const pageSize = ref(5)
const pageCurrent = ref(1)

const ruleFormRef = ref<FormInstance>()

const ruleForm = reactive<ApplyList>({
  applicantid: '',
  applicantname: '',
  approverid: '',
  approvername: '',
  note: '',
  reason: '',
  time: ['','']
})

const validatorTime = (rule: unknown, value: [DateModelType, DateModelType], callback: (arg?: Error) => void) => {
  if(!value[0] && !value[1]) {
    callback(new Error('请选择审批时间'))
  } else {
    callback()
  }
}

const rules = reactive<FormRules<typeof ruleForm>>({
  approvername: [
    { required: true, message: "请选择审批人", trigger: 'blur' },
  ],
  reason: [
    { required: true, message: "请选择审批事由", trigger: 'blur' },
  ],
  time: [
    { validator: validatorTime, trigger: 'blur' },
  ],
  note: [
    { required: true, message: "请填写备注", trigger: 'blur' },
  ],
})

const pageApplyList = computed(() => 
  applyList.value.slice((pageCurrent.value - 1)*pageSize.value, pageCurrent.value*pageSize.value)
)

const submitForm = (formEl: FormInstance | undefined) => {
  if (!formEl) return
  formEl.validate((valid) => {
    if (valid) {
      ruleForm.applicantid = userInfos.value._id as string
      ruleForm.applicantname = userInfos.value.name as string
      ruleForm.approverid = (approver.value.find(v => v.name === ruleForm.approvername) as {[index: string]: unknown})._id as string
      ruleForm.time[0] = moment(ruleForm.time[0]).format('YYYY-MM-DD hh:mm:ss')
      ruleForm.time[1] = moment(ruleForm.time[1]).format('YYYY-MM-DD hh:mm:ss')
      store.dispatch('checks/postApply', ruleForm).then(res => {
        if(res.data.errcode === 0) {
          store.dispatch('checks/getApply', { applicantid: userInfos.value._id }).then(res => {
            if(res.data.errcode === 0) {
              store.commit('checks/updateApplyList', res.data.rets)
            }
          })
          store.dispatch('news/putRemind', { userid: ruleForm.approverid, approver: true })
          ElMessage.success('添加审批成功')
          resetForm(ruleFormRef.value)
          handleClose()
        } else {
          ElMessage.error(res.data.errmsg)
        }
      })
    } else {
      console.log('error submit!')
    }
  })
}

const resetForm = (formEl: FormInstance | undefined) => {
  if(!formEl) return
  formEl.resetFields()
}

const handleChange = (value: number) => {
  pageCurrent.value = value
}

const handleClose = () => {
  dialogVisible.value = false
}

const handleOpen = () => {
  dialogVisible.value = true
}

</script>

<style scoped lang="scss">
.apply-title {
  margin: 20px;
  display: flex;
  justify-content: space-between;
}
.apply-table {
  margin: 10px;
  .el-pagination {
    float: right;
    margin: 10px;
  }
}
</style>
