// fontend/front-vue-vite/src/views/Sign/Sign.vue
<template>
  <el-descriptions border direction="vertical" :column="9">
    <el-descriptions-item label="月份">{{ month }}月</el-descriptions-item>
    <el-descriptions-item v-for="value, key in DetailKey" :key="key" :label="value">
      {{ detailValue[key] }}
    </el-descriptions-item>
    <el-descriptions-item label="操作">
      <el-button type="primary" plain size="small" @click="handleToException">查看详情</el-button>
    </el-descriptions-item>
    <el-descriptions-item label="考勤状态">
      <el-tag :type="detailState.type" size="small">{{ detailState.text }}</el-tag>
    </el-descriptions-item>
  </el-descriptions>
  <el-calendar v-model="date">
    <template #header>
      <el-button type="primary" @click="handlePutTime">在线签到</el-button>
      <el-space>
        <el-button plain>{{ year }}年</el-button>
        <el-select v-model="month" @change="handleChange">
          <el-option v-for="item in 12" :key="item" :value="item" :label="item + '月'" />
        </el-select>
      </el-space>
    </template>
    <template #date-cell="{ data }">
      <div>{{ renderDate(data.day) }}</div>
      <div class="show-time">{{ renderTime(data.day) }}</div>
    </template>
  </el-calendar>
</template>

<script setup lang="ts">
import { ref, reactive, watchEffect, defineComponent } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { toZero } from '@/utils/common'
import { useUserStore } from '@/stores/users';
import { useSignStore } from '@/stores/signs';
import { storeToRefs } from 'pinia';
defineComponent({
  name: 'SignView'
})

const router = useRouter()
const usersStore = useUserStore()
const signsStore = useSignStore()
const { infos: usersInfos } = storeToRefs(usersStore)
const { infos: signsInfos } = storeToRefs(signsStore)

const date = ref(new Date())
const year = date.value.getFullYear()
const month = ref(date.value.getMonth() + 1)

enum DetailKey {
  normal = '正常出勤',
  absent = '旷工',
  miss = '漏打卡',
  late = '迟到',
  early = '早退',
  lateAndEarly = '迟到并早退'
}

const detailValue = reactive({
  normal: 0,
  absent: 0,
  miss: 0,
  late: 0,
  early: 0,
  lateAndEarly: 0
})
const detailState = reactive({
  type: 'success' as 'success' | 'danger',
  text: '正常' as '正常' | '异常'
})

watchEffect((reset)=>{
  const detailMonth = ((signsInfos.value.detail as {[index: string]: unknown})[toZero(month.value)] as {[index: string]: unknown})
  for(const attr in detailMonth){
    switch( detailMonth[attr] ){
      case DetailKey.normal:
        detailValue.normal++
        break
      case DetailKey.absent:
        detailValue.absent++
        break
      case DetailKey.miss:
        detailValue.miss++
        break
      case DetailKey.late:
        detailValue.late++
        break
      case DetailKey.early:
        detailValue.early++
        break
      case DetailKey.lateAndEarly:
        detailValue.lateAndEarly++
        break
    }
  }
  for(const attr in detailValue){
    if( attr !== 'normal' && detailValue[attr as keyof typeof detailValue] !== 0){
      detailState.type = 'danger'
      detailState.text = '异常'
    }
  }
  reset(()=>{
    detailState.type = 'success'
    detailState.text = '正常'
    for(const attr in detailValue){
      detailValue[attr as keyof typeof detailValue] = 0
    }
  })
})

const handleChange = () => {
  date.value = new Date(`${year}.${month.value}`)
}
const handleToException = () => {
  router.push({
    path: '/exception',
    query: { month: month.value }
  });
}
const renderDate = (day: string) => {
  return day.split('-')[2];
}
const renderTime = (day: string) => {
  const [, month, date] = day.split('-');
  const ret = ((signsInfos.value.time as {[index: string]: unknown})[month] as {[index: string]: unknown})[date];
  if( Array.isArray(ret) ){
    return ret.join('-')
  }
}
const handlePutTime = () => {
  signsStore.putTimeAction({userid: usersInfos.value._id}).then((res)=>{
    if(res.data.errcode === 0){
      signsStore.updateInfos(res.data.infos) 
      ElMessage.success('签到成功')
    }
  })
}
</script>

<style scoped lang="scss">
.el-descriptions{
  margin: 10px;
}
.el-select{
  width: 80px;
}
.show-time{
  text-align: center;
  line-height: 40px;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}
</style>

// fontend/front-react/src/views/Sign/Sign.tsx
import React, { useState, useEffect } from 'react'
import styles from './Sign.module.scss'
import {
  Descriptions,
  Button,
  Tag,
  Calendar,
  Row,
  Space,
  Select,
  message,
} from 'antd'
import 'dayjs/locale/zh-cn'
import locale from 'antd/es/date-picker/locale/zh_CN'
import type { Dayjs } from 'dayjs'
import { useNavigate } from 'react-router-dom'
import { useSelector } from 'react-redux'
import { useAppDispatch } from '../../store'
import type { RootState } from '../../store'
import _ from 'lodash'
import {
  getTimeAction,
  putTimeAction,
  updateInfos,
} from '../../store/modules/signs'
import type { Infos } from '../../store/modules/signs'
import { toZero } from '../../utils/common'

const date = new Date()

enum DetailKey {
  normal = '正常出勤',
  absent = '旷工',
  miss = '漏打卡',
  late = '迟到',
  early = '早退',
  lateAndEarly = '迟到并早退',
}

const originDetailValue: Record<keyof typeof DetailKey, number> = {
  normal: 0,
  absent: 0,
  miss: 0,
  late: 0,
  early: 0,
  lateAndEarly: 0,
}

const originDetailState = {
  type: 'success' as 'success' | 'error',
  text: '正常' as '正常' | '异常',
}

export default function Sign() {
  const [month, setMonth] = useState(date.getMonth())
  const navigate = useNavigate()
  const signsInfos = useSelector((state: RootState) => state.signs.infos)
  const usersInfos = useSelector((state: RootState) => state.users.infos)
  const dispatch = useAppDispatch()
  const [detailValue, setDetailValue] = useState({ ...originDetailValue })
  const [detailState, setDetailState] = useState({ ...originDetailState })

  useEffect(() => {
    if (_.isEmpty(signsInfos)) {
      dispatch(getTimeAction({ userid: usersInfos._id as string })).then(
        (action) => {
          const { errcode, infos } = (
            action.payload as { [index: string]: unknown }
          ).data as { [index: string]: unknown }
          if (errcode === 0) {
            dispatch(updateInfos(infos as Infos))
          }
        }
      )
    }
  }, [signsInfos, usersInfos, dispatch])
  useEffect(() => {
    if (signsInfos.detail) {
      const detailMonth = (signsInfos.detail as { [index: string]: unknown })[
        toZero(month + 1)
      ] as { [index: string]: unknown }
      for (let attr in detailMonth) {
        switch (detailMonth[attr]) {
          case DetailKey.normal:
            originDetailValue.normal++
            break
          case DetailKey.absent:
            originDetailValue.absent++
            break
          case DetailKey.miss:
            originDetailValue.miss++
            break
          case DetailKey.late:
            originDetailValue.late++
            break
          case DetailKey.early:
            originDetailValue.early++
            break
          case DetailKey.lateAndEarly:
            originDetailValue.lateAndEarly++
            break
        }
      }
      setDetailValue({...originDetailValue})

      for(const attr in originDetailValue){
        if( attr !== 'normal' && originDetailValue[attr as keyof typeof originDetailValue] !== 0){
          setDetailState({
            type: 'error',
            text: '异常'
          })
        }
      }

    }
    return ()=>{  //更新前触发或销毁的时候
      setDetailState({
        type: 'success',
        text: '正常'
      })
      for(let attr in originDetailValue){
        originDetailValue[attr as keyof typeof originDetailValue] = 0;
      }
    }
  }, [month, signsInfos])

  const handlePutTime = () => {
    dispatch(putTimeAction({ userid: usersInfos._id as string })).then(
      (action) => {
        const { errcode, infos } = (
          action.payload as { [index: string]: unknown }
        ).data as { [index: string]: unknown }
        if (errcode === 0) {
          dispatch(updateInfos(infos as Infos))
          message.success('签到成功')
        }
      }
    )
  }
  const handleToException = () => {
    navigate(`/exception?month=${month+1}`)
  }
  const dateCellRender = (value: Dayjs) => {
    const month =
      signsInfos.time &&
      (signsInfos.time as { [index: string]: unknown })[
        toZero(value.month() + 1)
      ]
    const date =
      month && (month as { [index: string]: unknown })[toZero(value.date())]
    let ret = ''
    if (Array.isArray(date)) {
      ret = date.join(' - ')
    }
    return <div className={styles['show-time']}>{ret}</div>
  }
  return (
    <div>
      <Descriptions
        className={styles.descriptions}
        layout="vertical"
        column={9}
        bordered
      >
        <Descriptions.Item label="月份">{month + 1}月</Descriptions.Item>
        {Object.entries(DetailKey).map((v) => (
          <Descriptions.Item key={v[0]} label={v[1]}>
            {detailValue[v[0] as keyof typeof DetailKey]}
          </Descriptions.Item>
        ))}
        <Descriptions.Item label="操作">
          <Button type="primary" onClick={handleToException} ghost size="small">
            查看详情
          </Button>
        </Descriptions.Item>
        <Descriptions.Item label="考勤状态">
          <Tag color={detailState.type}>{detailState.text}</Tag>
        </Descriptions.Item>
      </Descriptions>
      <Calendar
        dateCellRender={dateCellRender}
        locale={locale}
        headerRender={({ value, type, onChange, onTypeChange }) => {
          const monthOptions = []
          for (let i = 0; i < 12; i++) {
            monthOptions.push(
              <Select.Option key={i} value={i}>
                {i + 1}月
              </Select.Option>
            )
          }
          return (
            <Row
              className={styles['calendar-header']}
              justify="space-between"
              align="middle"
            >
              <Button type="primary" onClick={handlePutTime}>
                在线签到
              </Button>
              <Space>
                <Button>{value.year()}年</Button>
                <Select
                  value={month}
                  onChange={(newMonth) => {
                    setMonth(newMonth)
                    onChange(value.clone().month(newMonth))
                  }}
                >
                  {monthOptions}
                </Select>
              </Space>
            </Row>
          )
        }}
      />
    </div>
  )
}
